version: "3"
services:
  db:
    image: hramos13/game-project-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: games
    restart: always
    ports:
      - 3306:3306

  api:
    image: hramos13/game-project-back:latest
    ports:
      - 3001:3001
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: mysql://root:root@db:3306/games
      JWT_SECRET: 1234567899oiuywriufbdsfldsv

  web:
    image: hramos13/game-project-front:latest
    ports:
      - 3000:3000
    depends_on:
      - api
    restart: always
